# Generated by Django 5.0.3 on 2024-04-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hat',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gender'),
        ),
        migrations.AlterField(
            model_name='pant',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gender'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gender'),
        ),
        migrations.AlterField(
            model_name='top',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gender'),
        ),
    ]
