# Generated by Django 5.0.3 on 2024-04-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='top',
            name='image',
        ),
        migrations.AddField(
            model_name='hat',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pant',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='top',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
