# Generated by Django 5.0.3 on 2024-04-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gender_alter_category_name_alter_hat_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='color',
        ),
        migrations.RemoveField(
            model_name='top',
            name='color',
        ),
    ]
